version: "3.1"


services:

  db:
    image: postgres:12.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: poc_postgres
      POSTGRES_PASSWORD: poc_postgres
      POSTGRES_DB: poc_postgres